### PR TITLE
update to fix pybtex

### PR DESCRIPTION
**Pull request by SimonGreenhill**

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
@tresoldi can you check why we've now got a BIPA error?

**Comment by tresoldi** [comment]
That is strange, @SimonGreenhill . I'm checking.

**Comment by SimonGreenhill** [comment]
ahh, the entry looks really weird: ```"bathe')              :"```, I'll cull it in lexemes.csv.

**Comment by tresoldi** [comment]
Yes, but still strange. Maybe your version of `pyclts`?

**Comment by SimonGreenhill** [comment]
yeah, that could also be it - i  was on 2.0, have just updated to pyclts-2.1.3, and rebuilding now.

**Comment by tresoldi** [comment]
But that is actually a gloss, so it could be `pylexibank` or something else with a wrong way of dealing with `FormSpec`

**Comment by tresoldi** [comment]
On my `release environment`, I get the following:

```
- **Varieties:** 1,011
- **Concepts:** 1,210
- **Lexemes:** 145,984
- **Sources:** 148
- **Synonymy:** 1.15
- **Invalid lexemes:** 0
- **Tokens:** 725,761
- **Segments:** 390 (0 BIPA errors, 0 CTLS sound class errors, 389 CLTS modified)
- **Inventory size (avg):** 27.46

```

**Comment by SimonGreenhill** [comment]
fixed :) 

```
- **Varieties:** 1,011
- **Concepts:** 1,210
- **Lexemes:** 145,983
- **Sources:** 148
- **Synonymy:** 1.15
- **Invalid lexemes:** 0
- **Tokens:** 725,756
- **Segments:** 390 (0 BIPA errors, 0 CTLS sound class errors, 389 CLTS modified)
- **Inventory size (avg):** 27.46
```

**Review by tresoldi — APPROVED** [review]

**Review by chrzyki — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
