### PR TITLE
Release prep & other fixes

### PR DESCRIPTION
**Pull request by chrzyki**
Okay, here's the 'proper' PR with the most-recent master, sorry again! Repeating from #25:

Hi @SimonGreenhill. Here's a small update for preparing another release of the TNG data. Are you okay with the changes to CONTRIBUTORS or would you prefer any changes?

This PR is not ready for merging insofar as that it contains manual a fix to the upstream data that needs to be verified (I wanted to be able to test/work through the whole pipeline) and potentially fixed upstream?:

```diff
diff --git a/raw/languages.json b/raw/languages.json
index fac6b01..8112598 100644
--- a/raw/languages.json
+++ b/raw/languages.json
@@ -4047,7 +4047,7 @@
         "classification": "Trans-New Guinea, Southeast Papuan, Goilalan, Fuyug",
         "dialect": "Kabana",
         "fullname": "Fuyug (Kabana Dialect)",
-        "glottocode": "fuyu124",
+        "glottocode": "fuyu1242",
         "id": 1703,
         "information": "Named variety in Williamson 1912, probably just a clan name",
         "isocode": "fuy",
@@ -4073,7 +4073,7 @@
         "classification": "Trans-New Guinea, Southeast Papuan, Goilalan, Fuyug",
         "dialect": "Korona",
         "fullname": "Fuyug (Korona Dialect)",
-        "glottocode": "fuyu124",
+        "glottocode": "fuyu1242",
         "id": 1702,
         "information": "Named variety in Williamson 1912, probably just a clan name",
         "isocode": "fuy",
@@ -4086,7 +4086,7 @@
         "classification": "Trans-New Guinea, Southeast Papuan, Goilalan, Fuyug",
         "dialect": "Mafulu",
         "fullname": "Fuyug (Mafulu Dialect)",
-        "glottocode": "fuyu124",
+        "glottocode": "fuyu1242",
         "id": 1705,
         "information": "Named variety in Williamson 1912, probably just a clan name",
         "isocode": "fuy",
@@ -4099,7 +4099,7 @@
         "classification": "Trans-New Guinea, Southeast Papuan, Goilalan, Fuyug",
         "dialect": "Sikube",
         "fullname": "Fuyug (Sikube Dialect)",
-        "glottocode": "fuyu124",
+        "glottocode": "fuyu1242",
         "id": 1704,
         "information": "Named variety in Williamson 1912, probably just a clan name",
         "isocode": "fuy",
@@ -13519,4 +13519,4 @@
         "resource_uri": "/api/v1/language/zorop/",
         "slug": "zorop"
     }
-]
\ No newline at end of file
+]
```

The upstream `raw/languages.json` has a Glottocode `fuyu124` which I assume should be (but I might be wrong) `fuyu1242`.

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
Hi, thanks @chrzyki  -- fixed upstream, can you rerun download and rebuild?

**Comment by SimonGreenhill** [comment]
Happy with adding @LinguList to CONTRIBUTORS - sorry that should have been done long ago

**Comment by chrzyki** [comment]
> Hi, thanks @chrzyki -- fixed upstream, can you rerun download and rebuild?

Awesome, thank you! Will do.

**Comment by chrzyki** [comment]
Thanks again, everything good with the upstream fixes. There are some profile fixes that could be done on lexemes introduced with a90e70f1b9e0a7ec44970fa9a14fe8af18bb8587 (+ two in the most recent data update):

| ID | LANGUAGE | CONCEPT | FORM | SEGMENTS |
|:---------------------------------|:-----------------|:------------------|:------------------|:----------------------------------|
| anjam-lalok-2018_forehead-1 | anjam-lalok | 2018_forehead | land͡ʒa | l a nd <s> <<͡>> </s> ʒ a |
| arandai-sebyar-1282_urine-1 | arandai-sebyar | 1282_urine | undʼuno | u nd <s> <<ʼ>> </s> u n o |
| arandai-sebyar-1296_six-1 | arandai-sebyar | 1296_six | gendʼi | g e nd <s> <<ʼ>> </s> i |
| arandai-sebyar-57_sand-1 | arandai-sebyar | 57_sand | kindʼai | k i nd <s> <<ʼ>> </s> a i |
| arandai-sebyar-888_nonot-1 | arandai-sebyar | 888_nonot | andʼa | a nd <s> <<ʼ>> </s> a |
| arandai-weriagar-1282_urine-1 | arandai-weriagar | 1282_urine | andʼuno | a nd <s> <<ʼ>> </s> u n o |
| arandai-weriagar-2116_slowly-1 | arandai-weriagar | 2116_slowly | nandʼu | n a nd <s> <<ʼ>> </s> u |
| arandai-weriagar-224_banana-1 | arandai-weriagar | 224_banana | undʼi | u nd <s> <<ʼ>> </s> i |
| arandai-weriagar-283_slow-1 | arandai-weriagar | 283_slow | nandʼu | n a nd <s> <<ʼ>> </s> u |
| arandai-weriagar-899_flyingfox-1 | arandai-weriagar | 899_flyingfox | kumandʼe | k u m a nd <s> <<ʼ>> </s> e |
| faita-2027_groundpossum-1 | faita | 2027_groundpossum | kindʷʌ | k i nd <s> <<ʷ>> </s> ʌ |
| fuyug-mafulu-896_elbow-1 | fuyug-mafulu | 896_elbow | bodol_'_u'_kodabe | b o d o l + + u + k o d a b e |
| kunimaipa-250_finger-1 | kunimaipa | 250_finger | mala_-_tiporotch | m a l a + + t i p o r o t c h |
| sam-buan-2018_forehead-1 | sam-buan | 2018_forehead | land͡ʒa | l a nd <s> <<͡>> </s> ʒ a |
| sam-songum-1629_faceforehead-1 | sam-songum | 1629_faceforehead | land͡ʒa | l a nd <s> <<͡>> </s> ʒ a |
| sam-wongbe-2018_forehead-1 | sam-wongbe | 2018_forehead | land͡ʒa | l a nd <s> <<͡>> </s> ʒ a |
| tsaukambo-60_small-1 | tsaukambo | 60_small | bændʒ͡ɔwɑˈtɔ | b æ nd ʒ <s> <<͡>> </s> ɔ w ɑ t ɔ |
| wanggom-60_small-1 | wanggom | 60_small | bæʔændʒ͡ɔʔ | b æ ʔ æ nd ʒ <s> <<͡>> </s> ɔ ʔ |
| yaqay-wairu-51_one-1 | yaqay-wairu | 51_one | diˈɣɑndʰ | d i ɣ ɑ nd <s> <<ʰ>> </s> |

Can also have a look at this later or do you have any preferences?

**Comment by FredericBlum** [comment]
@SimonGreenhill Could you add the missing fixes? This is one of the last datasets still requiring attention right now.

**Comment by SimonGreenhill** [comment]
all the arandai issues have been fixed upstream

**Comment by SimonGreenhill** [comment]
The others should be fixable by adding these to the profile -- 

ndʷ
ndʰ

... but how do you want the <<͡>> handled?

**Comment by LinguList** [comment]
CLTS ignores the bar, as it is not needed, if you have segmentation.

**Comment by LinguList** [comment]
ndʷ must be superscript-n + d + superscript-w
ndʰ must be superscript-n + d + supercript-h

CLTS requires nd to be modeled as pre-nasalized d.

**Comment by FredericBlum** [comment]
I have pushed a new commit that

- fixes the remaining orthography profiles
- Ignores languages that are part of the zgraggenmadang, mcelhanonhuon, and robinsonap datasets

@SimonGreenhill Are there any other Lexibank datasets that have been used as a source for TNG.org where we might want to avoid duplicates? E.g. johanssonsoundsymbolic, tryonsolomon, and abvdoceanic? Or are those independent digitizations? If everything is alright, we can merge and release.

**Comment by SimonGreenhill** [comment]
Thanks @FredericBlum -- but do we really want to remove the 'duplicates'? that makes this dataset not a faithful reflection of transnewguinea.org, and there can be revisions / fixes / cognates /etc in tng.org that are not in the original datasets? 

Surely the deduping should be handled at the lexibank level?

**Comment by LinguList** [comment]
@SimonGreenhill, the problem we have with TNG and some other datasets now is that:

1. there is a dedicated cldf-dataset, with a dedicated orthoprofile and a dedicated concept list in concepticon
2. TNG aggregates data like zgraggenmadang AGAIN

Lexibank has a greedy way of selecting the "best" dataset for a language. We just take the one that has more entries. But we want to curate what goes into Lexibank, so we have some direct intention of saying TNG/zgraggenmadang is to be refused over lexibank/zgraggenmadang (Lexibank selects but ONE variety to be reflected in the FormTable).

As TNG is also aggregating data from datasets in the lexibank repository, we have to make a choice, and the preference is the original datasets in lexibank.

The alternative is that TNG adopts the lexibank style and aggregates data itself from Lexibank, but as long as this is not in place, we need to make a decision for the data that goes into TNG/cldf and also into Lexibank 2.0.

**Comment by LinguList** [comment]
An example is the recent dataset I added for lexibank, [berrywestpapuan](https://github.com/lexibank/berrywestpapuan): if that goes into TNG, we have duplicated it, because it started out with lexibank. `zgraggenmadang` is similar. So my long-term suggestion is: TNG becomes an aggregator as lexibank, and we outsource individual datasets in the future, similar to what I did with berrywestpapuan. But as long as this is not accomplished, we keep the parts not in the lexibank repo (or a dedicated TNG repo with dedicated one-source-as-cldf-datasets) as our default to add languages we'd otherwise miss. We do the same with IDS now: if we get a "better" version of a sub-part, we prefer that and we reduce the core IDS by blacklisting the data (https://calc.hypotheses.org/7503). So our idea is to do the same here with TNG now. 

Or are there alternative ways to handle this? Obviously we do not want to have identical language varieties in lexibank that pull from the same sources...

**Comment by SimonGreenhill** [comment]
Hi Mattis -- this is a problem for all aggregator databases (ABVD, TNG, DIACL, etc etc). I think handling this way is a bad idea:

1. It's whack-a-mole -- how far into ABVD etc do you want to dig? who wants to spend time going through all these and blacklisting each and every thing? So now you've tagged some things as duplicates, but there's lots of other things that will be duplicates too that aren't as easy to spot e.g. the data collected in e.g. robinsonap is partly from primary literature. What do you do if TNG and robinsonap have both sourced the same list? you'd need to dedupe to the original rather than thinking robinsonap is the primary (...but the original is not in its own dataset, so then you need to judge which is "better". Good luck).

2. It's not catching changes that come in as added value into the aggregator datasets (which kind of goes against the whole lexibank idea of enhancing existing datasets).

3. It's a *major* disincentive to put your dataset into lexibank. If this goes ahead I'll want to make my own CLDF dataset of tng.org (and ABVD etc). People ask me how to get tng.org, I used to be able to point them to lexibank, now I'd have to say that there is some subset in lexibank, but if you want to get it all you need to download lexibank/tng, languages A,B and C from zgraggenmadang D,E,F from robinsonap. Easier to send them elsewhere.

4. I don't see why duplicates are actually a problem -- why deduplicate at all? what is a duplicate is often a useful bit of data: Is x the same across these datasets? how has it changed? is dataset x and faithful representation of y?

**Comment by xrotwang** [comment]
I agree that the filtering of duplicate content would be better done in lexibank-analysed, rather than here, because this dataset is supposed to contain the data from the provenance context "transnewguinea.org" - and having only a somewhat intransparently incomplete copy of this data here would seem odd.

That said, I also think we should incentivize aggregators like TNG to make their constituent data available in CLDF in a more "atomic" way. One of the lessons learned with lexibank (from my POV) is that such more narrowly focused datasets make it a lot easier to add value - be it orthography profiles or metadata. In addition, this way of adding value is a lot more transparent than comparing duplicate data between atomic datasets and aggregated data. While in theory possible, answering the question "is dataset x a faithful representation of y" right now is certainly difficult.

**Comment by SimonGreenhill** [comment]
I agree that narrow focus datasets is easier, but that's a lesson that took me 20 years to learn :)

**Comment by xrotwang** [comment]
To elaborate: In an ideal world, both - lexibank and TNG - would be aggregating from a pool of "atomic" datasets; both adding value in different ways. So I think of lexibank and TNG rather as *methods* not as *data*.

**Comment by xrotwang** [comment]
I guess, for lexibank 2.0 (i.e. lexibank-analysed), the alternatives are
- drop TNG entirely
- filter upon creation of lexibank-analysed (which is done anyway on a per-glottocode basis, right?)
- include TNG as is.

For the future we should aim at breaking out the atomic parts of aggregators, making the first option above more viable - or, possibly even better, realize that the "lexibank method" is understood well enough already for people to apply it to their own favorite aggregates of lexibank datasets themselves.

**Comment by LinguList** [comment]
I forgot I already had a solution in my head that would just leave TNG as is (just discussed that with @FredericBlum and @xrotwang):

1. we have a flag for each Form in a FormTable of Lexibank-Analysed, where we say 1 for the preferred form and 0 for the non-preferred duplicate
2. we include all forms in Lexibank, but flag them.

For aggregators like TNG, the future would be to drop them entirely and to work on exporting the individual datasets in there to individual repos (as we have done in part with Zgraggenmadang, etc.). 

For now, we can leave TNG, but if TNG keeps aggregating new data from cldf datasets, that are also ending up in Lexibank as individual cldf datasets, we must drop TNG. For now, it works to flag the data in question.

**Comment by FredericBlum** [comment]
Short clarification question: We create the flag in this dataset, or during the LBA conversion?

**Comment by xrotwang** [comment]
> Short clarification question: We create the flag in this dataset, or during the LBA conversion?

I'd say during LBA conversion.

**Comment by FredericBlum** [comment]
Ok. I have adapted this PR accordingly. Coukd you check if we can merge and release this now?

**Comment by SimonGreenhill** [comment]
thanks guys, I like the alternative solution and am happy for this to be merged now.

**Review by SimonGreenhill — APPROVED** [review]

**Pull request merged**
